### PR TITLE
feat: add -trimpath support for go build

### PR DESCRIPTION
**Pull request by hbagdi**

### CODE REVIEW

**Review by crazy-max — APPROVED** [review]
LGTM thanks

**Review by crazy-max — CHANGES_REQUESTED** [review]
Hum actually CI is not happy, might be a typo somewhere

**Comment by hbagdi** [comment]
@crazy-max There was a typo that messed up two commands in the shell script. Could you give this another try?

**Review by crazy-max — APPROVED** [review]
LGTM thanks

**Pull request merged**
